# First edge station profile (Pico W #1)
# Hardware:
# - LED/Relay channel 1 on GPIO15
# - Pushbutton on GPIO16 (to GND, internal pull-up)

WIFI_SSID = "YOUR_WIFI_SSID"
WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"

MQTT_BROKER = "172.16.3.205"
MQTT_PORT = 1883
MQTT_USERNAME = ""
MQTT_PASSWORD = ""
MQTT_KEEPALIVE = 60

WIFI_PM = None

# Optional runtime Wi-Fi credentials file (JSON)
WIFI_USE_CREDENTIAL_FILE = False
WIFI_CREDENTIALS_PATH = "wifi_credentials.json"

TEAM_ID = "TEAM-CHANTRAGREEN"
DEVICE_ID = "pico-w-01-led-btn"

PUBLISH_INTERVAL_SEC = 5
HEARTBEAT_INTERVAL_SEC = 30

# Keep humidity simulated for this profile (no DHT22 on GPIO16).
HUMIDITY_SOURCE = "simulated"
DHT22_PIN = 17

RELAYS = [
    {"id": "1", "pin": 15, "active_high": True},
]

BUTTON_ENABLED = True
BUTTON_ID = "1"
BUTTON_PIN = 16
BUTTON_PULL_UP = True
BUTTON_ACTIVE_LOW = True
BUTTON_DEBOUNCE_MS = 80
BUTTON_PRESS_TOGGLE_RELAY = True

# Long-press behavior
BUTTON_LONG_PRESS_ENABLED = True
BUTTON_LONG_PRESS_STAGE1_MS = 3000
BUTTON_LONG_PRESS_STAGE1_ACTION = "pairing_mode"
BUTTON_LONG_PRESS_STAGE2_MS = 8000
BUTTON_LONG_PRESS_STAGE2_ACTION = "reset_wifi_config"
PAIRING_MODE_DURATION_SEC = 180
LONG_PRESS_RESET_REBOOT = True

OFFLINE_QUEUE_MAX = 80
RECONNECT_BASE_SEC = 2
RECONNECT_MAX_SEC = 30

WATCHDOG_ENABLED = True
WATCHDOG_TIMEOUT_MS = 8000

LOOP_SLEEP_MS = 250
USE_LIGHT_SLEEP = True
CPU_FREQ_HZ = 125000000
